version: '3.5'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: product_dashboard_db
    ports:
      - "5432:5432"

networks:
  host:
    driver: bridge
